name: me.nykorrin.sucrose.Sucrose
authors: [CodedRed, Nykorrin]
version: ${project.version}
api-version: 1.17
main: me.nykorrin.sucrose.me.nykorrin.sucrose.Sucrose
website: https://youtu.be/DMNdcJyeP4k?list=PL65-DKRLvp3ZO2i1OK0tfRsZt-glkBpUV
description: And this one is called... Mist Flower Project 3, Version 17, Enlargement Trial.
commands:
  image:
    description: Convert an image into a map.